"""empty message

Revision ID: 0467313d6d4f
Revises: 7b72e756144a
Create Date: 2020-12-28 13:10:27.037407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0467313d6d4f'
down_revision = '7b72e756144a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookcab', sa.Column('cab_id', sa.Integer(), nullable=True))
    op.add_column('bookcab', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bookcab', 'customer', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'bookcab', 'cab', ['cab_id'], ['id'])
    op.add_column('cab', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cab', 'owner', ['owner_id'], ['id'])
    op.add_column('customer', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'password_hash')
    op.drop_constraint(None, 'cab', type_='foreignkey')
    op.drop_column('cab', 'owner_id')
    op.drop_constraint(None, 'bookcab', type_='foreignkey')
    op.drop_constraint(None, 'bookcab', type_='foreignkey')
    op.drop_column('bookcab', 'customer_id')
    op.drop_column('bookcab', 'cab_id')
    # ### end Alembic commands ###
