"""Changed table names

Revision ID: 075de013a018
Revises: 
Create Date: 2020-12-29 10:07:32.533478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075de013a018'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cab_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dname', sa.String(length=64), nullable=True),
    sa.Column('Vno', sa.String(length=64), nullable=True),
    sa.Column('Vtype', sa.String(length=64), nullable=True),
    sa.Column('From', sa.String(length=64), nullable=True),
    sa.Column('To', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cab_details_From'), 'cab_details', ['From'], unique=False)
    op.create_index(op.f('ix_cab_details_To'), 'cab_details', ['To'], unique=False)
    op.create_index(op.f('ix_cab_details_Vno'), 'cab_details', ['Vno'], unique=False)
    op.create_index(op.f('ix_cab_details_Vtype'), 'cab_details', ['Vtype'], unique=False)
    op.create_index(op.f('ix_cab_details_dname'), 'cab_details', ['dname'], unique=False)
    op.create_index(op.f('ix_cab_details_phone'), 'cab_details', ['phone'], unique=False)
    op.create_table('booked_cab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dname', sa.String(length=64), nullable=True),
    sa.Column('Vno', sa.String(length=64), nullable=True),
    sa.Column('Vtype', sa.String(length=64), nullable=True),
    sa.Column('From', sa.String(length=64), nullable=True),
    sa.Column('To', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('yname', sa.String(length=64), nullable=True),
    sa.Column('Bdate', sa.String(length=64), nullable=True),
    sa.Column('Btime', sa.String(length=64), nullable=True),
    sa.Column('cab_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cab_id'], ['cab_details.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booked_cab_Bdate'), 'booked_cab', ['Bdate'], unique=False)
    op.create_index(op.f('ix_booked_cab_Btime'), 'booked_cab', ['Btime'], unique=False)
    op.create_index(op.f('ix_booked_cab_From'), 'booked_cab', ['From'], unique=False)
    op.create_index(op.f('ix_booked_cab_To'), 'booked_cab', ['To'], unique=False)
    op.create_index(op.f('ix_booked_cab_Vno'), 'booked_cab', ['Vno'], unique=False)
    op.create_index(op.f('ix_booked_cab_Vtype'), 'booked_cab', ['Vtype'], unique=False)
    op.create_index(op.f('ix_booked_cab_dname'), 'booked_cab', ['dname'], unique=False)
    op.create_index(op.f('ix_booked_cab_phone'), 'booked_cab', ['phone'], unique=False)
    op.create_index(op.f('ix_booked_cab_yname'), 'booked_cab', ['yname'], unique=False)
    op.drop_index('ix_bookcab_Bdate', table_name='bookcab')
    op.drop_index('ix_bookcab_Btime', table_name='bookcab')
    op.drop_index('ix_bookcab_From', table_name='bookcab')
    op.drop_index('ix_bookcab_To', table_name='bookcab')
    op.drop_index('ix_bookcab_Vno', table_name='bookcab')
    op.drop_index('ix_bookcab_Vtype', table_name='bookcab')
    op.drop_index('ix_bookcab_dname', table_name='bookcab')
    op.drop_index('ix_bookcab_phone', table_name='bookcab')
    op.drop_index('ix_bookcab_yname', table_name='bookcab')
    op.drop_table('bookcab')
    op.drop_index('ix_cab_From', table_name='cab')
    op.drop_index('ix_cab_To', table_name='cab')
    op.drop_index('ix_cab_Vno', table_name='cab')
    op.drop_index('ix_cab_Vtype', table_name='cab')
    op.drop_index('ix_cab_dname', table_name='cab')
    op.drop_index('ix_cab_phone', table_name='cab')
    op.drop_table('cab')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cab',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('cab_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('dname', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('Vno', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('Vtype', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('From', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('To', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('flag', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], name='cab_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cab_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_cab_phone', 'cab', ['phone'], unique=False)
    op.create_index('ix_cab_dname', 'cab', ['dname'], unique=False)
    op.create_index('ix_cab_Vtype', 'cab', ['Vtype'], unique=False)
    op.create_index('ix_cab_Vno', 'cab', ['Vno'], unique=False)
    op.create_index('ix_cab_To', 'cab', ['To'], unique=False)
    op.create_index('ix_cab_From', 'cab', ['From'], unique=False)
    op.create_table('bookcab',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dname', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('Vno', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('Vtype', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('From', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('To', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('Bdate', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('Btime', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('cab_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('yname', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cab_id'], ['cab.id'], name='bookcab_cab_id_fkey'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='bookcab_customer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='bookcab_pkey')
    )
    op.create_index('ix_bookcab_yname', 'bookcab', ['yname'], unique=False)
    op.create_index('ix_bookcab_phone', 'bookcab', ['phone'], unique=False)
    op.create_index('ix_bookcab_dname', 'bookcab', ['dname'], unique=False)
    op.create_index('ix_bookcab_Vtype', 'bookcab', ['Vtype'], unique=False)
    op.create_index('ix_bookcab_Vno', 'bookcab', ['Vno'], unique=False)
    op.create_index('ix_bookcab_To', 'bookcab', ['To'], unique=False)
    op.create_index('ix_bookcab_From', 'bookcab', ['From'], unique=False)
    op.create_index('ix_bookcab_Btime', 'bookcab', ['Btime'], unique=False)
    op.create_index('ix_bookcab_Bdate', 'bookcab', ['Bdate'], unique=False)
    op.drop_index(op.f('ix_booked_cab_yname'), table_name='booked_cab')
    op.drop_index(op.f('ix_booked_cab_phone'), table_name='booked_cab')
    op.drop_index(op.f('ix_booked_cab_dname'), table_name='booked_cab')
    op.drop_index(op.f('ix_booked_cab_Vtype'), table_name='booked_cab')
    op.drop_index(op.f('ix_booked_cab_Vno'), table_name='booked_cab')
    op.drop_index(op.f('ix_booked_cab_To'), table_name='booked_cab')
    op.drop_index(op.f('ix_booked_cab_From'), table_name='booked_cab')
    op.drop_index(op.f('ix_booked_cab_Btime'), table_name='booked_cab')
    op.drop_index(op.f('ix_booked_cab_Bdate'), table_name='booked_cab')
    op.drop_table('booked_cab')
    op.drop_index(op.f('ix_cab_details_phone'), table_name='cab_details')
    op.drop_index(op.f('ix_cab_details_dname'), table_name='cab_details')
    op.drop_index(op.f('ix_cab_details_Vtype'), table_name='cab_details')
    op.drop_index(op.f('ix_cab_details_Vno'), table_name='cab_details')
    op.drop_index(op.f('ix_cab_details_To'), table_name='cab_details')
    op.drop_index(op.f('ix_cab_details_From'), table_name='cab_details')
    op.drop_table('cab_details')
    # ### end Alembic commands ###
