"""empty message

Revision ID: 6d13bdf2fd89
Revises: 
Create Date: 2020-11-30 16:16:30.520765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d13bdf2fd89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('phno', sa.Integer(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('dest', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_date'), 'customer', ['date'], unique=False)
    op.create_index(op.f('ix_customer_dest'), 'customer', ['dest'], unique=False)
    op.create_index(op.f('ix_customer_name'), 'customer', ['name'], unique=False)
    op.create_index(op.f('ix_customer_phno'), 'customer', ['phno'], unique=False)
    op.create_index(op.f('ix_customer_source'), 'customer', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_source'), table_name='customer')
    op.drop_index(op.f('ix_customer_phno'), table_name='customer')
    op.drop_index(op.f('ix_customer_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_dest'), table_name='customer')
    op.drop_index(op.f('ix_customer_date'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
