"""empty message

Revision ID: 6e55d3c2180e
Revises: 8adc12f02569
Create Date: 2020-12-28 16:36:44.206830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e55d3c2180e'
down_revision = '8adc12f02569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookcab', 'flag')
    op.add_column('cab', sa.Column('flag', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cab', 'flag')
    op.add_column('bookcab', sa.Column('flag', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
