"""empty message

Revision ID: 7b72e756144a
Revises: 7f4a1de4b866
Create Date: 2020-12-27 22:40:31.318215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b72e756144a'
down_revision = '7f4a1de4b866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bookcab_Yname', table_name='bookcab')
    op.drop_column('bookcab', 'Yname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookcab', sa.Column('Yname', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('ix_bookcab_Yname', 'bookcab', ['Yname'], unique=False)
    # ### end Alembic commands ###
