"""empty message

Revision ID: 7f4a1de4b866
Revises: ecbc5b2e9374
Create Date: 2020-12-27 17:07:54.988488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f4a1de4b866'
down_revision = 'ecbc5b2e9374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookcab', sa.Column('Yname', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_bookcab_Yname'), 'bookcab', ['Yname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookcab_Yname'), table_name='bookcab')
    op.drop_column('bookcab', 'Yname')
    # ### end Alembic commands ###
