"""empty message

Revision ID: 8adc12f02569
Revises: 0467313d6d4f
Create Date: 2020-12-28 16:23:45.155679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8adc12f02569'
down_revision = '0467313d6d4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookcab', sa.Column('flag', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookcab', 'flag')
    # ### end Alembic commands ###
