"""empty message

Revision ID: ecbc5b2e9374
Revises: 
Create Date: 2020-12-27 14:41:51.720022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecbc5b2e9374'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookcab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dname', sa.String(length=64), nullable=True),
    sa.Column('Vno', sa.String(length=64), nullable=True),
    sa.Column('Vtype', sa.String(length=64), nullable=True),
    sa.Column('From', sa.String(length=64), nullable=True),
    sa.Column('To', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('Bdate', sa.String(length=64), nullable=True),
    sa.Column('Btime', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookcab_Bdate'), 'bookcab', ['Bdate'], unique=False)
    op.create_index(op.f('ix_bookcab_Btime'), 'bookcab', ['Btime'], unique=False)
    op.create_index(op.f('ix_bookcab_From'), 'bookcab', ['From'], unique=False)
    op.create_index(op.f('ix_bookcab_To'), 'bookcab', ['To'], unique=False)
    op.create_index(op.f('ix_bookcab_Vno'), 'bookcab', ['Vno'], unique=False)
    op.create_index(op.f('ix_bookcab_Vtype'), 'bookcab', ['Vtype'], unique=False)
    op.create_index(op.f('ix_bookcab_dname'), 'bookcab', ['dname'], unique=False)
    op.create_index(op.f('ix_bookcab_phone'), 'bookcab', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookcab_phone'), table_name='bookcab')
    op.drop_index(op.f('ix_bookcab_dname'), table_name='bookcab')
    op.drop_index(op.f('ix_bookcab_Vtype'), table_name='bookcab')
    op.drop_index(op.f('ix_bookcab_Vno'), table_name='bookcab')
    op.drop_index(op.f('ix_bookcab_To'), table_name='bookcab')
    op.drop_index(op.f('ix_bookcab_From'), table_name='bookcab')
    op.drop_index(op.f('ix_bookcab_Btime'), table_name='bookcab')
    op.drop_index(op.f('ix_bookcab_Bdate'), table_name='bookcab')
    op.drop_table('bookcab')
    # ### end Alembic commands ###
